# Generated by Django 3.2.9 on 2021-12-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_ordermodel_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('views', models.CharField(max_length=500)),
                ('rating', models.IntegerField(max_length=2, default=99, blank=False)),
            ],
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),

    ]
