# Generated by Django 3.2.9 on 2021-12-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20211208_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=99, max_length=2),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='views',
            field=models.CharField(default='Add your views here', max_length=500),
        ),
    ]

