# Generated by Django 3.2.9 on 2021-12-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20211208_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='views',
            field=models.CharField(default='no comments', max_length=500),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),

    ]
